#!/usr/bin/env python
# -*- coding: utf-8 -*-

from datetime import date
from sys import exit

thetext = """
Demanà l'amic a son amat si havia en ell nulla cosa romasa a amar; e l'amat respós que ço per què l'amor de l'amic podia muntiplicar, era a amar.
Les carreres per les quals l'amic encerca son amat són llongues, perilloses, poblades de consideracions, de sospirs e de plors, e enluminades d'amors.
Ajustaren-se molts amadors a amar un amat qui els abundava tots d'amors; e cascú havia per cabal son amat e sos pensaments agradables, per los quals sentien plaents tribulacions.
Plorava l'amic e deïa: - ¿Tro a quant de temps cessaran tenebres en lo món, per ço que cessen les carreres infernals? Ni l'aigua, qui ha en costuma que decórrega a enjús, ¿quan serà l'hora que haja natura de pujar a ensús? Ni els innocents ¿quan seran més que els colpables?
—Ah! quan se gaubarà l'amic que muira per son amat? Ni l'amat, quan veurà son amic llanguir per sa amor?
Dix l'amic a l'amat: —Tu qui umples lo sol de resplendor, umple mon cor d'amor. Respòs l'amat: —Sens compliment d'amor no foren tos ulls en plor, ni tu vengut en est lloc veer ton amador.
Temptà l'amat son amic si amava perfectament; e demanà-li de què era la diferència qui és enfre presència e absència d'amat. Respòs l'amic: —D'innorància e oblidament, coneixença e remembrament.
Demanà l'amat a l'amic: —¿Has membrança de nulla cosa que t'haja guardonat, per ço cor me vols amar? Respòs: —Hoc, ver ço cor enfre los treballs e els plaers que em dónes, no en faç diferència.
—Digues, amic —dix l'amat—: ¿hauràs paciència si et doble tes llangors? —Hoc, ab que em dobles mes amors.
Dix l'amat a l'amic: —Saps, encara, què és amor? —Si no sabés què és amor, ¿sabera què és treball, tristícia e dolor?
Digueren a l'amic: —¿Per què no respons a ton amat qui t'apella? Respòs: —Ja m'aventur a greus perills per ço que a ell pervenga, e ja li parle desirant ses honors.
—Amic foll: ¿per què destruus ta persona e despens tos diners, e lleixes los delits d'aquest món e vas menyspreat enfre les gents? Respòs: —Per honrar los honraments de mon amat, qui per més hòmens és desamat, deshonrat, que honrat e amat.
—Digues, foll per amor: ¿e qual cosa és pus vesible, o l'amat en l'amic, o l'amic en l'amat? Respòs, e dix que l'amat és vist per amors, e l'amic per sospirs, e per plors, e treballs e dolors.
Encercava l'amic qui recomptàs a son amat com ell per sa amor sostenia greus treballs e moria; e atrobà son amat qui lligia en un llibre on eren escrites totes les llangors que amor li donaria per son amat, e tots los grats que n'havia.
Portà nostra Dona son Fill a l'amic per ço que li besàs son peu, e que escrivís en son llibre les virtuts de nostra Dona.
—Digues, aucell qui cantes: ¿est-te mes en guarda de mon amat per ço que el defena de desamor, e que muntiplic en tu amor? Respòs l'aucell: —¿E qui em fa cantar, mas tan solament lo Senyor d'amor, qui es té a deshonor desamor?
Enfre temor e esperança ha fet hostal amor, on viu de pensaments e mor per oblidaments com los fonaments són sobre los delits d'aquest món.
Qüestió lo enfre los ulls e la memòria de l'amic, cor los ulls deïen que mellor cosa és veer l'amat que membrar-lo, e la memòria dix que per lo remembrament puja l'aigua als ull e el cor s'enflama d'amor.
Demanà l'amic a l'enteniment e a la volentat qual era pus prop a son amat; e corregueren ambdós, e fo ans l'enteniment a son amat que la volentat.
Contrastaren-se l'amic e l'amat; e viu-ho un altre amic, qui plorà tan llongament tro hac feta pau e concordança enfre l'amat e l'amic.
Sospirs e plors vengren a jutjament a l'amat e demanaren-li per lo qual se sentia amat pus fortment. Jutjà l'amat que els sospirs són pus prop a amor, e los plors als ulls.
Venc l'amic beure a la font on hom qui no ama s'enamora com beu en la font, e doblaren sos llanguiments. E venc l'amat beure a la font per ço que sobredoblement doblàs a son amic ses amors, en les quals li doblàs llangors.
Malalte fo l'amic, e pensava'n l'amat: de mèrit lo peixia, e ab amor l'abeurava, e paciència lo colgava, d'humilitat lo vestia, ab veritat lo metjava.
Demanaren a l'amic on era son amat. Respòs: —Ve'l-vos en una casa pus noble que totes les altres nobilitats creades; e ve'l-vos en mes amors, e en mos llanguiments e en mos plors.
Digueren a l'amic: —On vas? —Venc de mon amat. On véns? —Vaig a mon amat. —Quan tornaràs? —Estaré ab mon amat. —Quant estarás ab ton amat? —Aitant de temps con seran en ell los meus pensaments.
Cantaven los aucells l'alba, e despertà's l'amic, qui és l'alba; e los aucells feniren llur cant, e l'amic morí per l'amat en l'alba.
Cantava l'aucell en lo verger de l'amat. Venc l'amie, qui dix a l'aucell: —Si no ens entenem per llenguatge, entenam-nos per amor; cor en lo teu cant se representa a mos ulls mon amat.
Hac son l'amic, qui molt havia treballat en cercar son amat; e hac paor que no oblidàs son amat. E Plorà, per ço que no s'adormís, ni son amat no los absent a son remembrament.
Encontraren-se l'amic e l'amat, e dix l'amic: —No cal que em parles; mas fé'm senyal ab tos ulls, qui són paraules a mon cor, con te do ço que demanes.
Desobeí l'amic son amat, e plorà l'amic. E l'amat venc morir en la gonella de son amic, per ço que l'amic recobràs ço que havia perdut; e donà-li major do que cell que perdut havia.
L'amat enamora l'amic, e no el plany de son llanguiment, per ço que pus fortment sia amat e en lo major llanguiment atrop l'amic plaer e reveniment.
Dix l'amic: —Turmenten-me los secrets de mon amat, com les mies obres los revelen, e cor la mia boca los té secrets e no els descobre a les gents.
Les condicions d'amor són que l'amic sia sofirent, pacient, humil, temorós, diligent, confiant, e que s'aventur a grans perills a honrar son amat. E les condicions de l'amat són que sia vertader, liberal, piadós, just, a son amic.
Encercava l'amic devoció en los munts e en los plans, per veer si era servit son amat; e atrobà'n defalliment en cascú d'aquests llocs. E per açó cavà en la terra, si hi atrobaria lo compliment, pus que per terra devoció ha defalliment.
—Digues, aucell qui cantes d'amor al meu amat: ¿per què em turmenta ab amor, qui m'ha pres a ésser son servidor? Respòs l'aucell: —Si no sostenes treballs per amor, ¿ab què amaries ton amat?
Consirós anava l'amic en les carreres de son amat, e encepegà, e caec enfre espines, les quals li foren semblants que fossen flors, e que son llit fos d'amors.
Demanaren a l'amic si camiaria per altre son amat. Respòs, e dix: —¿E qual altre es mellor ni pus noble que sobiran bé, eternal, infinit en granea, poder, saviea, amor, perfecció?
Cantava e plorava l'amic cants de son amat, e deïa que pus ivaçosa cosa es amor en coratge d'amador, que llamp en resplandor, ni tro en oïment; e pus viva es aigua en plor que en ondes de mar; e pus prop es sospir a amor que neu a blancor.
Demanaren a l'amic per què era son amat gloriós. Respòs: —Per ço cor és glòria. Digueren-li per què era poderós. Respòs: —Per ço cor es poder. Ni per què és savi: —Per ço cor és saviea. Ni per què és amable: —Per ço cor és amor.
Llevà's matí l'amic, e anava cercant son amat; e atrobà gents qui anaven per la via, e demanà si havien vist son amat. Respongueren-li dient quan lo aquella hora que son amat lo absent a sos ulls mentals. Respòs l'amic, e dix: —Anc, pus hac vist mon amat en mos pensaments, no lo absent a mos ulls corporals, cor totes coses vesibles me representen mon amat.
Ab ulls de pensaments, llanguiments, de sospirs e de plors, esguardava l'amic son amat; e ab ulls de gràcia, justícia, pietat, misericòrdia, liberalitat, l'amat esguardava son amic. E l'aucell cantava lo plaent esguardament damunt dit.
Les claus de les portes d'amor són daurades de consirers, sospirs e plors, e el cordó de les claus és de consciència, contrició, devoció, satisfació; e el porter es de justícia, misericòrdia.
Tocava l'amic a la porta de son amat ab colp d'amor, esperança. Oïa l'amat lo colp de son amic ab humilitat, pietat, paciència, caritat. Obriren les portes deïtat e humanitat, e entrava l'amic veer son amat.
Propietat e comunitat s'encontraren, e es mesclaren, per ço que fos amistat e benvolença enfre l'amic e l'amat.
Dos són los focs qui escalfen l'amor de l'amic: la un es bastit de desigs, plaers, cogitacions; l'altre és compost de temor, llanguiment, e de llàgremes e de plors.
Desirà l'amic soliditat, e anà estar tot sol per ço que hagués companyia de son amat, ab lo qual està tot sol enfre les gents.
Estava l'amic tot sol, sots l'ombra d'un bell arbre. Passaren hòmens per aquell lloc, e demanaren-li per què estava sol. E l'amic respòs que sol fo com los hac vists e oïts, e que d'abans era en companyia de son amat.
Ab senyals d'amor se parlaven l'amic e l'amat; e ab temor, pensaments, llàgremes e plors recomptava l'amic a l'amat sos llanguiments.
Dubtà l'amic que son amat no li fallís a ses majors necessitats. Desenamorà l'amat son amic. Hac contrició, penediment, l'amic en son cor; e l'amat reté al cor de l'amic esperança, caritat; e als ulls llágremes e plors, per ço que retornàs amor en l'amic.
Eguals coses só'n propinqüitat e llunyedat enfre l'amic e l'amat; cor enaixi com mesclament d'aigua e de vi, se mesclen les amors de l'amic e l'amat; enaixí con calor e llugor, s'encadenen llurs amors; e enaixí com esséncia e ésser, se convenen e s'acosten.
Dix l'amic a son amat: —En tu és mon sanament e mon llanguiment; e en pus fortment me sanes, pus creix mon llanguiment, e on pus me llangueixs, major sanitat me dónes. Respòs l'amat: —La tua amor és segell e empremta en mestres los meus honraments a les gents.
Veïa's pendre l'amic, e lligar, e ferir e auciure per amor de son amat. Demanaren-li aquells qui el turmentaven: —On és ton amat? Respòs: —Ve'l-vos en lo muntiplicament de mes amors e en la sustentació que em fa de mos turments.
Dix l'amic a l'amat: —Anc no fugí ni em partí de tu a amar, depús que t'hac conegut; cor en tu. e per tu e ab tu fui on que fos. Respòs l'amat: —Ni jo, depús que tu m'haguist conegut e amat, no t'oblidé, ni null temps no fiu contra tu engan ni falliment.
Anava l'amic per una ciutat com a foll, cantant de son amat; e demanaren-li les gents si havia perdut son senv. Respòs que son amat havia pres son voler, e que ell li havia donat son enteniment per açò era-li romàs tan solament lo remembrament, ab què remembrava son amat.
Dix l'amat: —Miracle es contra amor, d'amic qui s'adorm oblidant son amat. Respòs l'amic: —E miracle es contra amor si l'amat no desperta l'amic, pus que l'ha desirat.
Pujà-se'n lo cor de l'amic en les altees de l'amat, per ço que no los embargat a mar en l'abís d'aquest món. E con fo a l'amat, contemplà'l ab dolçor e plaer; e l'amat baixà'l a aquest món, per ço que el contemplàs e ab tribulacions e ab llanguiments.
Demanaren a l'amic: —Quals són tes riquees? Respòs: —Les pobretats que sostenc per mon amat. —E qual és ton repòs? —Lo llanguiment que em dóna amor. —E qui és ton metge? —La confiança que he de mon amat. —E qui és ton maestre? Respòs, e dix que les significances que les creatures donen de son amat.
Cantava l'aucell en un ram de fulles e de flors, e lo vent menava les fulles e aportava odor de les flors. Demanava l'amic a l'aucell què significava lo moviment de les fulles ni l'odor de les flors. Respòs: —Les fulles signifiquen en llur moviment, obediència; e l'odor, sufre e malanança.
Anava l'amic desirant son amat, e encontrà's ab dos amics qui ab amor e ab plors se saludaren, e s'abraçaren e es besaren. Esmortí's l'amic: tan fortment li remembraren los dos amics son amat.
Cogità l'amic en la mort, e hac paor tro que remembrà son amat. E cridà a les gents qui li estaven davant: —Ah, senyors! Amats per ço que mort ni perills no temats, a honrar mon amat.
Demanaren a l'amic on comentaran primerament ses amors. Respòs que en les noblees de son amat; e que d'aquell començament s'enclinarien a amar si mateix e son proïsme, e en desamar engan e falliment.
—Digues, foll: si et desamava ton amat, què faries? Respòs, e dix que amaria per ço que no morís, con sia cosa que desamor sia mort, e amor sia vida.
Demanaren a l'amic quina cosa era perseverança. Dix que perseverança era benanança e malanança en amic perseverant en amar, honrar, servir son amat ab fortitudo, paciència, esperança.
Dix l'amic a son amat que el pagàs del temps en què l'havia servit. Comptà l'amat los pensaments, e els desigs, e els plors, e els perills e els treballs que havia sostenguts son amic per sa amor; e afegí en aquell compte, eternal benauirança, e donà si mateix en paga a son amic.
Demanaren a l'amic qual cosa era benanança. Respòs que malanança sostenguda per amor.
—Digues, foll: quina cosa es malanança? —Membrança de les deshonors qui són fetes a mon amat, digne de tots honraments.
Remirava l'amic un lloc en lo qual havia vist son amat, e deïa: —Ah, lloc qui em representes les belles costumes de mon amat! Diràs a mon amat que jo sostenc, per sa amor, treball, e malanança. Respòs lo lloc: —Con en mi era ton amat, soferia per ta amor major treball e malanança que tots los altres treballs ni les altres malanançes que amor pot donar a sos servidors.
Deïa l'amic a son amat:—Tu est tot, e per tot, e en tot, e ab tot. Tu vull tot, per ço que haja e sia tot mi. Respòs l'amat: —No em pots haver tot sens que tu no sies de mi. E dix l'amic: —Hages-me tot, e jo tu tot. Respòs l'amat: —¿Què haurà ton fill, ton frare e ton pare? Dix l'amic: —Tu est tal tot, que pots abundar a ésser tot de cascú qui es dóna a tu tot.
Estec e perllongà l'amic sos pensaments en la granea e en la durabletat de son amat, e no hi atrobà començament, ni mijà, ni fi. E dix l'amat: —Què mesures, foll? Respòs l'amic: —Mesur menor ab major, e defalliment ab compliment, e començament ab infinita, eternitat, per ço que humilitat, paciència, caritat, esperança, ne sien pus fortment en ma membrança.
Les vies d'amor són llongues e breus per ço cor amor és clara, pura, nèdea, vera, subtil, simple, forts, diligent, llugorosa, abundosa de novells pensaments e d'antics remembraments.
Demanaren a l'amic quals són los fruits d'amor. Respòs: Plaers, cogitaments, desigs, sospirs, ànsies, treballs, perills, turments, llanguiments. Sens aitals fruits no es lleixa amor tocar a sos servidors.
Estaven moltes gents denant l'amic, qui es clamava de son amat com no creixia ses amors; e clamava's d'amor com li donava treballs ni dolors. Escusà's l'amat, dient que los treballs e les dolors d'on acusava amor, eren muntiplicaments d'amors.
—Digues, foll: com no parles? —Ni què és ço en què estàs embarbesclat, consirós? Respòs: —En les bellees de mon amat, e en lo ressemblament de les benanances e de les dolors que m'aduen e em donen amors.
—Digues, foll: ¿qual cosa lo enans: o ton cor, o amor?—. Respòs, e dix que en un temps foren son cor e amor; cor si no ho fossen, lo cor no fóra creat a amar, ni amor no fóra creada a cogitar.
Demanaren al foll on començà enans sa amor: o en los secrets de son amat, o en revelar-los a les gents. Respòs, e dix que amor no hi fa null departiment, com és en son compliment; cor ab secret té l'amic secret los secrets de son amat, e ab secret los revela, e ab revelació los té secrets.
Secret d'amor sens revelació, dóna passió e llanguiment; e revelar amor dóna temor per frevor. E per açó l'amic en totes maneres ha llanguiment.
Apellà amor sos amadors, e dix-los que li demanassen los dons qui li eren pus desirables e pus plaents. E ells demanaren a amor que els vestís e els ornàs de sos afaiçonaments, per ço que fossen a l'amat pus agradables.
Cridà l'amic en alt a les gents, e dix que amor los manava que amassen en anant e en seent, e en vetlant e en dorment, e en parlant e en callant, e en comprant e en venent, e en plorant e en rient, e en plaer e en llanguiment, e en guanyant e en perdent; e en qualsque coses faessen, en totes amassen, cor d'amor n'havien manament.
—Digues, foll: quan venc en tu amor? Respòs: —En aquell temps que m'enriquí, e em poblà mon cor de pensaments, desirers, sospirs, llanguiments, e abundà mos ulls de llàgremes e de plors. —Què t'aportà amor? —Belles faiçons, honraments e valors de mon amat. —En què vengren? —En membrança e en enteniment. —Ab què els reebist? —Ab caritat, esperança. —Ab què els guardes? —Ab justicia, prudència, fortitudo, temprança.
Cantava l'amat e deïa que poc sabia l'amic d'amor si havia vergonya de lloar son amat, ni si el temia honrar en aquells llocs on pus fortment és deshonras; e poc sap d'amar qui s'enuja de malanança; ni qui es desespera de son amat, no fa concordança d'amor, esperança.
Tramès lletres l'amic a son amat, en les quals li dix si havia altre amador qui li ajudàs a portar e a soferir los greus afanys que sosté per sa amor. E l'amat rescrisc a son amic dient que no ha ab què faça vers ell injúria ni falliment.
Demanaren a l'amat, de l'amor de son amic. Respòs que l'amor de son amic és mesclament de plaer e malanança, e de temor, ardiment.
Demanaren a l'amic, de l'amor de l'amat. Respòs que l'amor de son amat és influència d'infinida bonea, eternitat, poder, saviea, caritat, perfecció; la qual influencia ha l'amat a l'amie.
—Digues, foll: quina cosa és meravella? Respòs: —Amar més les coses absents que les presents; e amar més les coses vesibles corruptibles, que les invisibles incorruptibles.
Encercava l'amic son amat, e atrobà un home qui moria sens amor; e dix que gran damnatge era d'home qui moria a nulla mort sens amor. E per açò dix l'amic a l'home qui moria: —Digues: per què mors sens amor? Respòs: —Per ço cor sens amor vivia.
Demanà l'amic a son amat qual cosa era major: o amor o amar. Respòs l'amat, e dix que, en creatura, amor és l'arbre e amar és lo fruit, e els treballs e els llanguiments són les flors e les fulles; e en Déu, amor e amar són una cosa mateixa, sens negun treball, llanguiment.
Estava l'amic en llanguiments e en tristícia per sobre abundància de pensaments; e tramès precs a son amat que li trametés un llibre en fossen escrites ses faiçons, per ço que li donàs alcun reme¡. L'amat tramès aquell llibre a son amic, e doblaren a l'amic sos treballs e sos llanguiments.
Malalte fo l'amic per amor, e entrà'l veer un metge qui muntiplicà ses llangors e sos pensaments; e sanat fo l'amic en aquella hora.
Apartaren-se l'amic e amor, e tenien solaç de l'amat; e representà's l'amat. Plorà l'amic e esvaneí's amor en l'esmortiment de l'amic. Reviscolà l'amat son amic com li remembrà ses faiçons.
Deïa l'amic a l'amat que per moltes carreres venia a son cor e es representava a sos ulls, e per molts noms lo nomenava sa paraula; mas l'amor ab què l'avidava e el mortificava no era mas una tan solament.
Entresenya's l'amat, a son amic, de vermells e novells vestiments; e estén sos braços per ço que l'abraç, e enclina son cap per co que li do un besar, e està en alt per ço que el pusca atrobar.
Absentà's l'amat a son amic, encercava l'amic son amat ab memòria e ab enteniment, per ço que el pogués amar. Atrobà l'amic son amat; demanà-li on havia estat. Respòs: —En l'absència de ton remembrament e en la innoráncia de ta intel·ligència.
—Digues, foll: ¿has vergonya de les gents con te veen plorar per ton amat? Respòs que vergonya sens pecat és per defalliment d'amor qui no sap amar.
Sembrava l'amat en lo cor de l'amic desigs, sospirs, virtuts e amors. Regava l'amic les sements ab llàgremes e ab plors.
Sembrava l'amat en lo cors de l'amic treballs, tribulacions, llanguiments. Sanava l'amic son cors ab esperança, devoció, paciència, consolacions.
A una gran festa tenc l'amat gran cort de molts honrats barons, e féu gran convits e gran dons. Venc l'amic a aquella cort; dix-li l'amat: —Qui t'ha apellat a venir a ma cort? Respòs l'amic: —Necessitat e amors m'han fet venir veer tes faiçons e tots capteniments.
Demanaren a l'amic de qui era. Respòs: —D'amor. —De què est? —D'amor. —Qui t'ha engenrat? —Amor. —On nasquist? —En amor. —Qui t'ha nodrit? —Amor. —De què vius? —D'amor. —Com has nom? —Amor. —D'on véns? —D'amor. —On vas? —A amor. —On estàs? —En amor. —Has altra cosa mas amor? —. Respòs: —Hoc, colpes e torts contra mon amat. —Ha en ton amat perdó? —. Dix l'amic que en son amat era misericordia e justícia, e per açò era son hostal enfre temor e esperança.
Absentà's l'amat a l'amic, e encercà'l l'amie ab sos pensaments; e demanava'l a les gents ab llenguatge d'amor.
Atrobà l'amic son amat qui estava menyspreat enfre les gents, e dix a l'amat que gran injúria era feta a sos honraments. Respòs l'amat, e dix que ell prenia deshonor per fretura de fervents e devots amadors. Plorà l'amic e multiplicaran ses dolors; aconsolava'l l'amat mostrant-li sos capteniments.
Lo llum de la cambra de l'amat venc intuminar la cambra de l'amic, per ço que en gitàs tenebres e que l'omplís de plaers, e de llangors e de pensaments. E l'amic gità de sa cambra totes coses, per ço que hi cabés son amat.
Demanaren a l'amic quin senyal faïa son amat en son gamfanó. Respòs que d'home mort. Digueren-li per què faïa aital senyal. Respòs: —Per ço cor lo home mort crucificat, e per ço que aquells qui es gaben que son sos amadors, seguesquen son esclau.
Venc l'amat albergar a l'hostal de son amic, e lo majordome demanà-li hostalatge. Mas l'amic dix que son amat devia ésser albergat en perdó.
Acompanyaren-se memòria e volentat, e pujaren en lo munt de l'amat per ço que l'enteniment s'exalçàs, e l'amor se doblàs en amar l'amat.
Tots jorns són sospirs e plors missatges enfre l'amic e l'amat, per ço que sia enfre ambdós solaç, companyia, e amistat, e benvolença.
Envorava l'amic son amat, e tramès-li sos pensaments, per ço que li aportassen de son amat la benanança en la qual l'havia tengut llongament.
Benefici donà l'amat a son amic, de plors, sospirs, llangors, pensaments e dolors; ab lo qual benefici servia l'amic son amat.
Pregà l'amic son amat que li donàs llarguea, pau, honrament en est món, e l'amat demostrà ses faiçons al remembrament e l'enteniment de l'amic, e donà's a la volentat per object.
Demanaren a l'amic en què està honrament. Respòs que en entendre e amar son amat. E demanaren-li en què està deshonor. Respòs que en oblidar, desamar son amat.
—Turmentava'm amor tro que li hac dit que tu eres present als meus turments; e adoncs amor afluixà mos llanguiments, e tu, per guardó, muntipliquist amor, qui em doblà mos turments.
—Encontré en la via d'amor amador qui no parlava; ab plors, magres faiçons, llanguiments, acusava amor e blasmaya. Escusava's amor ab lleialtat, esperança, paciència, devoció, fortitudo, temprança, benanança. E per açò blasmé l'amador qui d'amor se clamava, pus que tan nobles dons li donava amor.
Cantava l'amic e deïa: —Oh, con gran malanança és amor! Ah, con gran benauirança és amar mon amat, qui ama sos amadors ab infinida amor eternal, complida en tots acabaments!
Anava l'amic en una terra estranya en cuidava atrobar son amat, e en la via assaltejaren-lo dos lleons. Paor hac de mort l'amic, per ço cor desirava viure per servir son amat; e tramès son remembrament a son amat, per ço que amor fos a sos traspassaments, per la qual amor mills pogués sostenir la mort. Dementre que l'amic remembrava l'amat, los lleons vengren humilment a l'amic, al qual lleparen les llàgremes de sos ulls qui ploraven, e les mans e els peus li besaren. E l'amic anà en pau encercar son amat.
Anava l'amic per munts e per plans, e no podia trobar portal on pogués eixir del carçre d'amor qui llongament havia tengut en presó son cors, e sos pensaments e tots sos desirers e plaers.
Dementre que l'amic anava enaixí treballat, atroba un ermità qui dormia prés d'una bella font. Despertà l'amic l'ermita, dient si havia vist, en somniant, son amant. Respòs l'ermità, e dix que egualment eren encarcerats sos pensaments en lo carçre d'amor, en vetllant e en dorment. Molt plac a l'amic com havia atrobat companyó en presó; e ploraren ambdós, cor l'amat no havia molts d'aitals amadors.
No ha en l'amat nulla cosa en què l'amic no haja ànsia e tribulació, ni l'amic no ha cosa en si en què l'amat no haja plaer e senyoria; e per açò l'amor de l'amat és en acció e l'amor de l'amic en llanguiment, passió.
En un ram cantava un aucell, e deïa que ell daria un novell pensament a amador que li'n donà's dos. Donà l'aucell lo novell pensament a l'amic, e l'amic donà'n dos a l'aucell, per ço que alleujàs sos turments; e l'amic senti muntiplicades ses dolors.
Encontraren-se l'amic e l'amat, e foren testimonis de llur encontrament saluts, abraçaments, e besars, e llàgremes e plors. E demanà l'amat a l'amic, de son estament; e l'amic lo embarbesclat en presència de son amat.
Contrastaren-se l'amic e l'amat, e pacificaren-los llurs amors; e fo qüestió qual amor hi mes major amistat.
Amava l'amic tots aquells qui temien son amat, e havia temor de tots aquells qui no temien son amat; e per açó fo qüestió qual era major en l'amic: o amor o temor.
Jurcava l'amic a seguir son amat, e passava per una carrera on havia un mal lleó qui auceïa tot home qui en passava pererosament e sens devoció.
Deïa l'amic: —Qui no tem mon amat, a tembre li cové totes coses; e qui tem mon amat, audàcia e ardiment li cové en totes coses.
Demanaren a l'amic d'ocasió, e dix que ocasió és plaer en penitència, e enteniment en consciència, e esperança en paciència, e sanitat en abstinència, consolació en remembrament, e amor en diligència, e lleialtat, en vergonya, e riquea en pobretat, e pau en obediència, e guerra en malvolença.
Enllumenà amor lo nuvolat qui es mes enfre l'amic e l'amat; e féu-lo enaixí llugorós e resplendent con és la lluna en la nit, e l'estel en l'alba, e lo sol en lo dia, e l'enteniment en la volentat. E per aquell nuvolat tan llugurós se parlen l'amic e l'amat.
Demanaren a l'amic quals tenebres són majors. Respòs que l'absència de son amat. Demanaren-li qual és la major resplendor, e dix que la presència de son amat.
Lo senyal de l'amat apar en l'amic, qui per amor és en tribulacions, sospirs, e plors, pensaments, e en menyspreament de les gents.
Escrivia l'amic aquestes paraules: —Alegra's mon amat, cor a ell tramet mos pensaments, e per ell ploren mos ulls, e sens llanguiments no viu, ni sent, ni veig, ni oig, ni he odoraments.
—Ah, enteniment, volentat! lladrats, e despertats los grans cans qui dormen, oblidants mon amat. Ah, ulls!: plorats. Ah cor!: sospirats. Ah memòria!: membrats la deshonor de mon amat, la qual li fan aquells que ell ha tan honrats.
—Muntiplica l'enemistat qui és enfre les gents e mon amat, e promet dons e guardons mon amat, e menaça ab justícia, saviea. E memòria e volentat menyspreen ses menaces e sos prometiments.
Acostava's l'amat a l'amic per ço que l'aconsolàs e el conhortàs dels llanguiments que sostenia, e dels plors que havia; e en més l'amat a l'amic s'acostava, pus fortment plorava e llanguia l'amic per les deshonors que planyia de son amat.
Ab ploma d'amor e ab aigua de plors, e en carta de passió, escrivia l'amic unes lletres a son amat, en les quals li deia que devoció se tardava e amor se moria, e falliment e error muntiplicaven sos enemics.
Nuaven—se les amors de l'amic e l'amat ab membrança, enteniment, volentat, per ço que l'amic e l'amat no es partissen; e la corda en què les dues amors se nuaven era de pensaments, llanguiments, sospirs e plors.
Jaia l'amic en llit d'amor; los llençols eren de plaers, e lo cobertor era de llanguiments, e el coixí era de plors. E era qüestió si el drap del coixí era del drap dels llençols o del cobertor.
Vestia l'amat son amic mantell, cota, gonella; e capell li faïa d'amor, e camisa de pensaments, e calces de tribulacions, e garlanda de plors.
Pregava l'amat son amic que no l'oblidàs. Deïa l'amic que no el podia oblidar, pus que no el podia innorar.
Deïa l'amat que en aquells llocs on és més temut a lloar, lo lloàs e l'escusàs. Deïa l'amic que d'amor lo bastàs. Responia l'amat que per sa amor s'era encarnat e penjat per morir.
Deïa l'amic al seu car amat que li mostràs manera con lo pogués fer conèixer e amar e lloar a les gents. Ompli l'amat son amic de devoció, paciència, caritat, tribulacions, pensaments, sospirs, e plors; e en lo cor de l'amic fo audàcia en lloar son amat, e en sa boca foren llaors de son amat, e en sa volentat lo menyspreament de lo blasme de les gents qui jutgen falsament.
Deïa l'amic a les gents aquestes paraules: —Qui vertaderament remembra mon amat, oblida, en les circumstàncies de son remembrament, totes coses; e qui totes coses oblida per membrar son amat, de totes coses lo defèn mon amat, e part li dóna de totes coses.
Demanaren a l'amic de què naixia amor, ni de què vivia, ni per què moria. Respòs l'amic que amors naixia del remembrament, e vivia d'intel·ligència, e moria per oblidament.
Oblidà l'amic tot ço qui es dejús lo sobirà cel, per ço que l'enteniment pogués pus alt pujar a conèixer l'amat lo qual la volentat desija preïcar, contemplar.
Anava's l'amic combatre per honrar son amat, e menà en sa companyia fe, esperança, caritat, justícia, prudència, fortitudo, temprança, ab què vencés los enemics de son amat. Fóra venqut l'amic, si no li ajudàs son amat a significar ses nobilitats a son amic.
Passar volia l'amic a la darrerana fi per la qual amava son amat, e les altres fins donaven-li embargament en son passatge; e per açò llongs desigs e pensaments diven a l'amic tristícia e llanguiment.
Gaubava's e alegrava's l'amic en les noblees de son amat; llanguia l'amic per sobrecogitacions e pensaments. E era qüestió qual sentia pus fortment, o els plaers o els turments.
Missatge era l'amic als prínceps crestians, e als infeels, per son amat, per ço que els mostràs l'art e els començaments a conèixer, amar, l'amat.
Si veus amador honrat de nobles vestiments, honrat per vanaglòria, gras per menjar e dormir, sàpies que en aquell veus damnació e turments. E si veus amador pobrament vestit, menyspreat per les gents, descolorit e magre per dejunar e vetlar, sàpies que en aquell veus salvació e perdurable benedicció.
Plany-se l'amic, e clama's lo cor de calor d'amor. Morse l'amic, plora'l l'amat, e dóna-li consolació de paciència, esperança, guardó.
Plorava l'amic ço que havia perdut; e no era qui el pogués consolar, per ço cor sos perdiments eren inrecuperables.
Creada ha Déus la nit a cogitar e a vetlar l'amic en les noblees de son amat; e cuidava's l'amic que l'hagués creada a reposar e a dormir aquells qui son treballats per amor.
Escarnien e reprenien les gents l'amic per ço cor anava com a foll per amor. E l'amic menyspreava llurs escarns, e reprenia les gents per ço cor no amaven son amat.
Deia l'amic: —Vestit són de drap vilment, mas amor vest de plaents pensaments mon cor, e lo cors de plors, llanguiments, passions.
Cantava l'amat, e deia: —Endrecen-se los meus lloadors en lloar mes valors; e los enemics de mos honraments turmenten-los e han-los en menyspreament. E per açò he tramès a mon amic que planga e plor ma deshonor; e els seus plants e els seus plors són nats de mes amors.
Jurava l'amic a l'amat que per sa amor amava e sostenia treballs e passions; e per açò pregava l'amat que l'amàs e de sos treballs passió hagués. Jurà l'amat que natura e proprietat era de sa amor que amàs tots aquells qui l'amaven, e que hagués pietat d'aquells qui per sa amor treball sostenien. Alegrà's l'amic, e consolà's en la natura e en la proprietat essencial de son amat.
Vedà la paraula l'amat a son amic, e aconsolava's l'amic en l'esguardament de son amat.
Tant plorà e cridà l'amic a son amat, tro que l'amat davallà de les altees sobiranes dels cels, e venc en terra plorar, e plànyer, e morir per amor, e per nodrir los hòmens a amar, e a conèixer, lloar sos honraments.
Blasmava l'amic los crestians com no meten lo nom de son amat. Jesucrist, primerament en llurs lletres, per ço que li faessen l'honor que els sarraïns fan a Mafumet, qui fo home galiador, al qual fan honor con lo nomenen primerament en llurs lletres.
Encontrà l'amic un escuder qui anava consirós e era magre, descolorit e pobrament vestit; e saludà l'amic dient que Déus l'endreçàs a trobar son amat. E l'amic li demanà en què l'havia conegut. E l'escuder li dix que los uns secrets d'amors revelen los altres; e per açò han coneixença, los amadors, los uns dels altres.
Les noblees, e els honraments e les bones obres de l'amat son tresor e riquees de l'amic. E lo tresor de l'amat son los pensaments, e els desigs, e els turments, e els plors e els llanguiments que l'amic sosté per honrar e amar son amat.
Grans hosts e grans companyes se són ajustades d'espirits d'amors, e porten senya d'amor, on és la figura e el senyal de llur amat; e no volen menar en llur companyia null home qui sia sens amor, per ço que llur amat no hi prenga deshonor.
Los hòmens qui es depenyen folls per ajustar diners, mouen l'amic a ésser foll per amor; e la vergonya que l'amic ha de les gents a anar con a foll, dóna manera a l'amic d'on haja amor e preu de les gents. E per açò és qüestió qual dels dos moviments es major ocasió d'amor.
En tristícia ha amor mès l'amic per sobrecogitaments; e cantà l'amat, e alegrà's l'amic com l'hac oït. E lo qüestió qual dels dos fo major ocasió a muntiplicar amor en l'amic.
En los secrets de l'amic són revelats los secrets de l'amat, e en los secrets de l'amat són revelats los secrets de l'amic. E és qüestió qual dels dos secrets és major ocasió de revelació.
Demanaren al foll per quals senyals era conegut son amat. Respòs, e dix que per misericòrdia, pietat, estant en volentat essencialment, sens negú camiament.
Per l'especial amor que l'amic havia a l'amat, amava lo bé comú sobre lo bé especial, per ço que comunament los son amat conegut, lloat, desirat.
Amor e desamor s'encontraren en un verger on parlaven secretament l'amic e l'amat; e amor demanà a desamor per qual entenció era venguda en aquell lloc: e respòs desamor que per desenamorar l'amic e per deshonrar l'amat. Molt desplac a l'amat e a l'amic ço que deia desamor; e muntiplicaren amor per ço que vencés e destruís desamor.
—Digues, foll: ¿en què et sens major volentat: o en amar, o en aïrar? Respòs que en amar, per ço cor aïrava per tal que pogués amar.
—Digues, amador: ¿en qué has mes d'enteniment: o en entendre veritat, o falsetat? Repòs que en entendre veritat. —Per què?—Cor entén falsetat per ço que pusca mills entendre veritat.
Apercebé l'amic que era amat per son amat, e demaná a l'amat si sa amor e sa misericordia eren en ell una cosa mateixa. Atorgá l'amat que, en sa esséncia, no han diferencia sa amor ni sa misericordia. E per a@ó dix l'amic per qué el turmeintava sa amor, e per qué no el guaria sa misericordia, de ses llangors. E respós l'amat que la misericordia li doná les llangors per Qo que ab aquelles honras pus perfetam'ent sa amor.
L'amic volc anar en una terra estranya per honrar son amat, e volc-se desmerxar per ço que nos los pres en lo camí. E anc no poc desmerxar de sos ulls plors, ni de sa cara magres faiçons e groga color, ni de son cor plants, pensaments, sospirs, tristícia, llanguiments; e per açò lo pres en lo viatge, e lliurat a turments per los enemics de son amat.
Estava pres l'amic en lo carçre d'amor. Pensaments, desigs e remembraments lo guardaven e l'encadenaven per ço que no fugís a son amat; llanguiments lo turmentaven; paciència, esperança lo consolaven. Morira's l'amic; mas l'amat li demostrà son estament, e reviscolà l'amic.
Encontrà l'amic son amat; conec l'amic son amat, e plorà. Reprès l'amat son amic per ço cor no plorava ans que l'hagués conegut; e demanà-li en què l'havia conegut, pus que no plorava. Respòs l'amic que en lo remembrament, e en l'enteniment, e en sa volentat, on lo multiplicament encontinent que lo present a sos ulls corporals.
Demanà l'amat a l'amic que era amor. Repòs que presència de faiçons e de paraules d'amat en cor sospirant d'amador, e llanguiment per desig e per plors en cor d'amic.
Amor és bulliment d'audàcia e de temor per frevor; e amor és final volentat a desirar son amat. E amor és aquella cosa qui aucís l'amic con oí cantar de les bellees de son amat. E amor és ço què és mort, e en què està tots jorns ma volentat.
Devoció e enyorament trameteren, per missatgers, pensaments al cor de l'amic, per ço que pujàs l'aigua als ulls qui volien cessar dels plors en los quals havien llongament estats.
Deïa l'amic: —Si vosaltres, amadors, volets foc, venits a mon cor e encenets vostres llàntees e si volets aigua, venits als meus ulls, qui decorren de llàgremes; e si volets pensaments d'amor, venits-los pendre a mes cogitacions.
Esdevenc-se un dia que l'amic cogitava en la gran amor que havia a son amat, e en los grans treballs e perills en què havia estat llongament per sa amor; e considera que sos guaardons fossen grans. Dementre que l'amic cogitava en esta manera, ell remembrà que pagat l'havia son amat, per ço cor l'havia enamorat de ses faiçons, e cor per sa amor li havia donats llanguiments.
Torcava l'amic sa cara e sos ulls de plors que sostenia per amor, per ço que no descobrís los llanguiments que li donava son amat; lo qual dix a son amic per què celava los senyals d'amor als altres amadors, los quals li havia donats per qo que els enamoràs d'honrar ses valors.
—Digues, home qui vas com a foll per amor: ¿tro a quant de temps seràs serf e sotsmès a plorar e a sostenir treballs e llanguiments? Respòs: —Tro al temps que mon amat, de l'ànima e del cors farà en mi departiment.
—Digues foll: has diners? Respòs: —He amat. —Has viles, ni castells, ni ciutats, comdats ni dugats? Respòs: —He amors, pensaments, plors, desirers, treballs, llanguiments, qui son mellors que emperis ni regnats.
Demanaren a l'amic en què coneixia la sentència de son amat. Respòs que en l'egualtat de plaers e llanguiments, a la qual son amat jutjava sos amadors.
—Digues, foll: ¿qui sap més d'amor: o aquel¡ qui n'ha plaer, o aquell qui n'ha treballs e llanguiments? Respòs, e dix que la un sens l'altre no en pot haver coneixença.
Demanaren a l'amic per què no s'escusava dels falliments e de los falsos crims que les genis l'acusaven. Respòs que a escusar havia son amat, que les gents blasmaven falsament; e que home, on pot caer engan e error, no es quaix digne de nulla escusació.
—Digues foll: ¿per què escuses amor com treballa e turmenta ton cors e ton cor? Respòs: —Per ço cor multiplica mos mèrits e ma benauirança.
Coniplanyia's l'amic de son amat con tan greument lo faïa turmentar a amor; e escusava's l'amat muntiplicant a l'amic treballs e perills, pensaments e llàgremes e plors.
—Digues, foll: per què escuses los colpables? Respòs: —Per ço que no sia semblant als acusants los innocents e els colpables.
Llevava l'amat l'enteniment a entendre ses altees, per ço que l'amic enclinàs son remembrament a membrar sos defalliments, e la volentat los menyspreàs e pujàs amar los acabaments de l'amat.
. Cantava l'amic de son amat, e deïa que tant li portava bona volentat, que totes les coses que aïrava per sa amor li eren piaents e benanances majors que les coses que amava sens l'amor de son amat.
Anava l'amic per una gran ciutat, e demanava si trobaria null home ab qui pogués parlar a sa guisa de son amat. E mostraren-li un home pobre qui plorava per amor e cercava companyó ab qui pogués parlar d'amor.
Estava l'amic pensiu e embarbesclat coro podien pendre començaments sos treballs, de les noblees de son amat, qui ha en si mateix tanta de benauirança.
Estaven les cogitacions de l'amic enfre oblidança de sos turments e entre membrança de sos plaers: cor los plaers que ha d'amor li obliden la malanança, e les turments que sosté per amor li remembren la benanança que ha per amor.
Demanaren a l'amic si era possible cosa que son amat lo desenamoràs. Respòs que no, dementre que la memòria membràs e l'enteniment entenés les nobleses de son amat.
—Digues, foll: ¿de què es fa la major comparació e semblança? Respòs: —D'amic e amat. Demanaren-li per qual raó. Respòs que per amor, qui estava entre ambdós.
Demanaren a l'amat si havia haüda null temps pietat. Respòs que si no hagués haüda pietat, no hagra enamorat l'amic, ni l'hagra turmentat de sospirs, e de plors, e de treballs e llangors.
En un gran boscatge era l'amic, qui anava cercar son amat; e atrobà veritat e falsetat qui es contrastaven de son amat, cor veritat lo lloava e falsetat lo blasmava. E per açò l'amic cridà amor que ajudàs a veritat.
Venc temptació a l'amic per ço que li absentàs son amat, e que la memòria se despertàs e recobràs la presència de son amat, membrant aquell pus fortment que no l'havia membrat, per ço que l'enteniment mes a ensús los llevat a entendre, e la volentat a amar, son amat.
Oblidà un dia l'amic son amat, e membrà en altre dia que l'havia oblidat. E en aquell dia en lo qual l'amic membrava que son amat oblidat havia, lo l'amic en tristícia e en dolor, e en glòria e en benanança, per oblidament e per membrança.
Tan fortment desirava l'amic llaors e honraments de son amat, que dubtava que els membràs; e tan fortment airava les deshonors de son amat, que dubtava que les airàs. E per açò l'amic estava embarbesclat, enfre amor e temor, per son amat.
Moria l'amic per plaer, e vivia per llanguiments; e els plaers e els turments s'ajustaven e s'unien en ésser una cosa mateixa en la volentat de l'amic. E por açò l'amic en un temps mateix moria e vivia.
Oblidar e innorar volgra l'amic son amal una hora tan solament, per ço que hagués alcun repòs a sos llanguiments. Mas, cor li fóra passió l'oblidament e la innorància, hac paciència, e exalçà son enteniment e sa memòria a contemplar son amat.
Tant amava l'amic son amat, que de tot ço que li deïa lo creïa, e tant lo desirava entendre, que tot ço que n'oïa dir volia entendre per raons necessàries. E per açò l'amor de l'amic estava enfre creença e intel·ligència.
Demanaren a l'amic qual cosa era pus lluny de son coratge; e ell respòs que desamor. E demanaren-li per qual raó. Respòs que per ço cor ço qui era pus prop a son coratge era amor, qui és contrari de desamor.
—Digues, foll: has enveja? Respòs: —Hoc, totes les vegades que oblit la llarguea e les riquees de mon amat.
—Digues, amador: has riquea? Respòs que: —Hoc: amor. —Has pobrea? —Hoc: amor. —Per què? —Per ço cor no és amor major, e cor no enamora molts amadors a honrar los honraments de mon amat.
—Digues, amant: on es ton poder? Respòs: —En lo poder de mon amat. —Ab què t'esforces contra tos enemics? —Ab les forces de mon amat. —Ab què et conhortes? —Ab los tresors eternals de mon amat.
—Digues, foil: ¿qual ames mes: o la misericòrdia de ton amat, o la justícia de ton amat? Respòs que tant li covenia amar e tembre justícia, que nulla majoritat de voler no devia haver en sa volentat a amar nulla cosa sobre la justícia de son amat.
Combatien-se colpes e mèrits en la consciència e en la volentat de l'amic; e justícia, membrança, muntiplicaven consciència; e misericòrdia, esperança, muntiplicaven benanança en la volentat de l'amat. E per açò los mèrits, vencien colpes e torts en la penitència de l'amic.
Afermava l'amic que en son amat era tota perfecció: e negava que en son amat no havia null defalliment. E per açò era qüestió qual era major: o l'afermació, o la negació.
Eclipse lo en lo cel, e tenebres en la terra; e per açò l'amic remembrà que pecat li havia llongament absentat son amat de son voler, per la qual absència tenebres havien exilada la llugor de son enteniment, ab la qual se representa l'amat a sos amadors.
Venc amor en l'amic, a la qual amor l'amic demanà què volia. E amor li dix que ella era venguda en ell per ço que l'acostumàs e el nodris en tal manera que, a la mort, pogués vençre sos mortals enemics.
Malalta lo amor con l'amic oblidà son amat; e malalte és l'amic, cor, per sobremembrar, son amat li dóna treballs, ànsies, e llanguiments.
Atrobà l'amic un home qui moria sens amor. Plorà l'amic la deshonor que l'amat prenia en la mort d'aquell home qui moria sens amor, e dix a aquell home per què moria sens amor; e ell respòs que per ço cor no havia qui li hagués donada coneixença d'amor ni qui l'hagués nodrit a ésser amador. E per açò l'amic sospirà en plorant e dix: —Ah, devoció! ¿quan serets major, per ço que la colpa sia menor e que lo meu amat haja molts fervents, ardits lloadors, amadors, qui no dubten a lloar sos honraments
Temptà l'amic amor si es poria sostenir en son coratge sens que no remembràs son amat; e cessà son cor de pensar e sos ulls de plorar; e aniquilà's amor, e romàs l'amic embarbesclat, e demanà a les gents si havien vista amor.
Amor, amar, amic e amat se covenen tan fortment en l'amat, que una actualitat són en essència, e diverses coses son l'amic e l'amat concordants sens nulla contrarietat e diversitat d'essència. E per açò l'amat és amable sobre totes altres amors.
—Digues, foll: per què has tan gran amor? Respòs: —Cor llong e perillós és lo viatge en lo qual vaig cercar mon amat. Ab gran feix lo'm cové encercar, e ivaçosament me cové anar; e totes aquestes coses no poria complir sens gran amor.
Vetlava, dejunava, plorava, almoina faïa, e en terres estranyes anava l'amic per ço que pogués a son amat moure sa volentat, e enamorar sos sotsmeses per honrar sos honraments.
Si no abasta l'amor de l'amic a moure son amat a pietat a perdó, abasta l'amor de l'amat a donar a ses creatures gràcia e benedicció.
—Digues, foll: ¿per qual cosa pots ésser pus semblant a ton amat? Respòs: —Per entendre a amar de tot mon poder les faiçons de mon amat.
Demanaren a l'amic si son amat havia defalliment de nulles coses, e respòs que hoc: d'amadors, lloadors, a honrar ses valors.
Feria l'amat lo cor de son amic ab vergues d'amor, per ço que li faés amar l'arbre d'on l'amat collí les vergues ab què fér sos amadors; en lo qual arbre soferí mort, e llangors e deshonors per restaurar a amor los amadors que perduts havia.
Encontrà l'amic son amat, e viu-lo molt noble e poderos, e digne de tot honrament; e dix-li que fortment se meravellava de les gents, qui tan poc l'amaven, e el coneixien e l'honraven, com ell ne los tan digne. E l'amat li respòs dient que ell havia pres molt gran engan en go que havia creat home per go que en los amat, conegut, honrat; e de mil hòmens, los cent lo temien e l'amaven tan solament; e de los cent, los noranta lo temien per ço que no els donàs pena, e los deu l'amaven per ço que els donàs glòria; e no era quaix qui l'amàs per sa bonea e sa nobilitat. Con l'amic oí aquestes paraules, plorà fortment en la deshonor de son amat, e dix: —Amat, qui tant has donat a home e tant l'has honrat, per què home tant tu en oblit?
Lloava l'amic son amat, e deïa que ell havia traspassat on, cor ell és lla on no pot atènyer on. E per açò com demanaren a l'amic en era son amat, respòs: —És; mas no es sabia on; emperò sabia que son amat és en son remembrament.
Comprà l'amat ab sos honraments un home esclau e sotsmès a pensaments, llanguiments, sospirs, e plors; e demaná-li què menjava ni bevia. Respòs que ço que ell volia. Demanà-li què vestia. Respòs que ço que ell volia. Dix l'amat: —Has gens de volentat? Respòs que serf e sostmès no ha altre voler mas obeir a son senyor e son amat.
Demanà l'amat a son amic si havia paciència. Respòs que totes coses li plaïen; e per açò no havia ab què hagués paciència; cor qui no havia senyoria en sa volentat, no podia ésser impacient.
Amor se donava a qui es volia; e cor a molts hòmens no es donava e los amadors fortment no enamorava, pus n'havia llibertat, per açò l'amic d'amor se clamava, e amor acusava a son amat. Mas amor s'escusava dient que ella no era contra franca volentat, per ço cor gran mèrit e gran glòria des¡rava a sos amadors.
Gran contrast e gran discòrdia lo enfre l'amic e amor, per ço cor l'amic s'ujava dels treballs que sostenia per amor. E era qüestió si era per defalliment d'amor, o de l'amic; e vengren-ne a jutjament de l'amat, lo qual puní l'amic ab llanguiment, e guaardonà-lo ab muntiplicament d'amor.
Qüestió lo si amor era pus prop a pensament o a paciència. Solvé l'amic la qüestió, e dix que amor és engenrada en los pensaments, e és sostentada en la paciència.
Veïns de l'amic són los bells capteniments de l'amat, e los veïns de l'amat són los pensaments de son amic, e los treballs e els plors que sosté per amor.
Volc pujar molt altament la volentat de l'amic per ço que molt amàs son amat, e manà a l'enteniment que pujàs a tot son poder; e l'enteniment ho manà al remembrament. E tots tres pujaren contemplar l'amat en sos honraments.
Partí's volentat de l'amic e donà's a l'amat; e l'amat mès en presó la volentat en l'amic, per ço que los per ell amat e servit.
Deïa l'amic: —No es cuit mon amat que jo sia departit a amar altre amat; cor amor m'ha tot ajustat a amar un amat tan solament. Respòs l'amat, e dix: —No es cuit mon amic que jo sia amat e servit per ell tan solament, ans he molts amadors per qui són amat pus fortment e pus llongament que per sa amor.
Deïa l'amic a son amat: —Amable amat: tu has mes ulls acostumats e nodrits a veer, e mes orelles a oir, tos honraments; e per açò és acostumat mon cor a pensaments, per los quals has acostumats mos ulls a plorar e mon cors a llanguir. Respòs l'amat a l'amic e dix que sens aitals costumes e nodriments no fóra escrit en lo llibre son nom, en lo qual són escrits tots aquells qui vénen a eternas benedicció, e son delits llurs noms del llibre on són escrits aquells qui van a eternal maledicció.
En lo cor de l'amic s'ajusten los nobles capteniments de l'amat, e muntipliquen los pensaments e els treballs en l'amic, lo qual fóra finit e mort si l'amat muntiplicàs en los pensaments de l'amic pus de sos honraments.
Venc l'amat albergar a l'hostal de son amic, e féu-li son amic llit de pensaments; e servien-li sospirs e plors. E pagà l'amat son hostal, de remembraments.
Mesclà amor los treballs e els plaers en los pensaments de l'amic; e clamaren-se los plaers d'aquell mesclament, e acusaren amor a l'amat; e feniren e deliren los plaers, con l'amat los hacs departits dels turments que amor dóna a sos amadors.
Los senyals de les amors que l'amicfa a son amat son: en lo començament plors, e en lo mig tribulacions, e en la fi mort. E per aquells senyals l'amic preica los amadors de son amat.
Assoliava's l'amic, a acompanyaven son cor pensaments, e sos ulls llàgremes e plors, e son cors afliccions e dejunis. E com l'amic tornava en la companyia de les gents, desemparaven-lo totes les coses damunt dites, e estava l'amic tot sol enfre les gents.
Amor és mar tribulada d'ondes e de vents, qui no ha port ni ribatge. Pereix l'amic en la mar, e en son perill pereixen sos turments e neixen sos complimens.
—Digues, foll: què és amor? Respòs: —Amor és concordança de tesòrica e de pràctica a una fi, a la qual se mou lo compliment de la volentat de l'amic, per ço que faca a les gents honrar e servir son amat. E és qüestió si la fi se cové pus fortment ab la volentat de l'amic qui desija ésser ab son amat.
Demanaren a l'amic qui era son amat. Respòs que ço qui el faïa amar, desirar, llanguir, sospirar, plorar, escarnir, morir.
Demanaren a l'amat qui era son amic. Respòs que aquell qui per honrar e lloar sos honraments no dubtava nulles coses, e qui a totes coses renunciava per obeir sos manaments e sos consells.
—Digues, foll: ¿qual feix es pus feixuc e pus greu: o treballs per amor, o treballs per desamor? Respòs que ho demanàs als hòmens qui fan penitència per amor de son amat o per temor dels turments infernals.
Adormí's l'amic e morí amor, cor no hac de què visquès. Despertà's l'amic e reviscolà amor en los pensaments que l'amic tramès a son amat.
Deïa l'amic que ciència infusa venia de volentat, devoció, oració, e ciència adquisita venia d'estudi, enteniment. E per açò és qüestió qual ciència és pus tost en l'amic, ni qual li és pus agradable, ni qual es major en l'amic.
—Digues, foll: d'on has tes necessitats? Respòs: —De pensaments, e de desirar, adorar, treballar, perseverança. —E d'on has totes aquestes coses? Respòs: —D'amor. —E d'on has amor? —De mon amat. —E d'on has ton amat? —De si mateix tan solament.
—Digues, foll: vols ésser franc de totes coses? Respòs que hoc, exeptat son amat. —Vols ésser catiu? Respòs que: —Hoc de sospirs, e pensaments, treballs, e perills e exils, plors, a servir mon amat, al qual son creat per lloar ses valors.
Turmentava amor l'amic per lo qual turment plorava e planvia l'amic. Cridava'l son amat que s'acostàs a ell per ço que sanàs. On pus l'amic a son amat s'acostava, pus fortment amor lo turmentava, cor mes d'amor sentia. E cor més de plaers sentia en més amava, pus fortment l'amat de sos llanguiments lo sanava.
Malalta era amor. Metjava-la l'amic ab paciència, perseverança, obediència, esperança guaria l'amor. Emmalaltia l'amic; sanava-lo l'amat donant-li remembrament de ses virtuts e de sos honraments.
—Digues, foll: què és solitudo? Respòs: —Solaç e companyia d'amic e amat. —E què és solaç e companyia? Respòs que solitudo estant en coratge d'amic qui no membra mas tan solament son amat.
Qüestió lo feta a l'amic: —¿On és major perill: en sostenir treballs per amor, o benanances? Acordà's l'amic ab son amat, e dix que perills per malanances són per impaciència, e perills per benanances són per desconeixença.
Solvé l'amat amor, e llicencià les gents que en prenguessen a tota llur volentat; e a penes atrobà amor qui la metés en son coratge. E per açò plorà l'amic e hac tristícia de la deshonor que amor pren sajús enfre nós, per falses amadors e per hòmens desconeixents.
Aucí amor en lo coratge de son vertader amic totes coses, per ço que hi pogués viure e caber; e hagra mort l'amic si no hagués membrança de son amat.
Havia en l'amic dos pensaments: la un cogitava tots jorns en l'essència e en les virtuts de son amat; e l'altre cogitava en les obres de son amat. E per açò era qüestió qual pensament era pus llugorós, pus agradable a l'amat e a l'amic.
Morí l'amic per força de gran amor. Soterrà'l en sa terra l'amat, en la qual fo l'amic ressucitat. E és qüestió l'amic de qual reebé major do.
En la presó de l'amat eren malanances, perills, llanguiments, deshonors, estranyedats, per ço que no embargassen son amic a lloar sos honraments e a enamorar los hómens qui l'han en menyspreament.
Estava l'amic un dia denant molts hòmens que son amat havia en est món massa honrats, per ço cor lo deshonraven en llurs pensaments. Aquells menyspreaven son amat e escarnien sos servidors. Plorà l'amic, tira sos cabells, bate sa cara e rompé sos vestiments; e cridà altament: —¿Fo anc fet tan gran falliments com menysprear mon amat?
—Digues, foll: vols morir? Respòs que: —Hoc, en los delits d'aquest món e en los pensaments dels maleïts qui obliden e deshonren mon amat; en los quals pensaments no vull ésser entès ni volgut, pus que no hi és mon amat.
—Si tu, foll, dius veritat, seràs per les gents ferit, e escarnit, reprès, turmentat e mort. Respòs: —Segons aitals paraules, se segueix que si deïa falsies, los lloat, amat, servit, hontal per les gents, e defès dels amadors de mon amat.
Falses lloadors blasmaven un dia l'amic en presència de son amat. Havia l'amic paciència, e l'amat justícia, saviea, poder. E l'amic amà més ésser blasmat e reprès, que ésser negú dels falses blasmadors.
Sembrava l'amat diverses sements en lo cor de son amic, d'on naixia, e fullava, e floria e granava un fruit tan solament. E és qüestió si d'aquell fruit poden néixer diverses sements.
Sobre amor està molt altament l'amat, e dejús amor està molt baixament l'amic. E amor, qui està en lo mig, davalla l'amat a l'amic, e puja l'amic a l'amat. E del davallament e pujament, viu e pren començament l'amor per la qual llangueix l'amic e és servit l'amat.
A la dreta part d'amor està l'amat, e l'amic està a la sinestra; e per açò sens que l'amic no pas per amor, no pot pervenir a son amat.
E denant amor està l'amat e detràs l'amat està l'amic. E per açò l'amic no pot pervenir a amor tro que ha passats sos pensaments e sos desirers per l'amat.
Fa l'amat a son amic tres semblants a si mateix amats, en honraments, e valors. E enamora's l'amic de tots tres egualment, jatsia que l'amor sia una tan solament, a significança de la unitat, una en tres amats essencialment.
Vestí's l'amat del drap en era vestit son amic, per ço que los son companyó en glòria eternalment. E per açò l'amic desirà tots jorns vermells vestiments, per ço que el drap sia mills semblant als vestiments de son amat.
—Digues, foll: què faïa ton amat ans que el món fos? Respòs: —Covenia's a ésser per diverses proprietats eternals, personals, infinides, on son amic e amat.
Plorava e havia tristícia l'amic com veïa a los infeels innorantment perdre son amat; e alegrava's en la justícia de son amat, qui turmentava aquells qui el coneixien e li eren desobedients. E per açò fo-li feta qüestió qual era major: o sa tristícia, o sa alegrança, ni si havia major benanança com veia honrar son amat, o major malanança com lo vela deshonrar.
Esguardava l'amic son amat en la major diferència e concordança de virtuts, e en la major contrarietat de virtuts e de vicis, e en ésser perfecció, qui es covenen pus fortment sens defalliment e no ésser, que ab defalliment e ab no ésser.
Los secrets de son amat veia l'amic, per diversitat, concordança, qui li revelaven pluralitat, unitat en son amat, per major conveniment d'essència sens contrarietat.
Digueren a l'amic que si corrupció, qui és contra ésser en ço qui és contra generació, qui és contra no ésser, era eternalment corrompent corromput, impossible cosa seria que no ésser ni fi se concordàs ab la corrupció ni el corromput. On, per estes paraules, l'amic viu en son amat generació eternal.
Si los falsetat ço per què l'amic pot mes amar son amat, fóra veritat ço per què l'amic no pot tant amar son amat: e si açò los enaixí, seguira's que defalliment los de major e de veritat en l'amat, e hagra en l'amat concordança de falsetat e menor.
Lloava l'amic son amat, e deia que si son amat ha major possibilitat a perfecció e major impossibilitat a imperfecció, cové que son amat sia simple, pura, actualitat en essència e en operació. On, dementre que l'amic enaixí lloava son amat, li era revelada la trinitat de son amat.
Veïa l'amic en nombre d'un e de tres major concordança que en altre nombre, per ço cor tota forma corporal venia de no ésser a ésser per lo nombre damunt dit. E per açò l'amic esguardava la unitat e la trinitat de son amat per la major concordança de nombre.
L'amic lloava lo poder, e el saber e el voler de son amat, qui havien creades totes coses, enfora pecat; lo qual pecat no fóra sens lo poder, e el saber e el voler de son amat; al qual pecat no son ocasió lo poder, ni el saber ni el voler de son amat.
Lloava e amava l'amic son amat com l'havia creat e li havia donades totes coses; e lloava'l e amava'l com li plac pendre sa semblanza e sa natura. E d'açò cové ésser feta qüestió qual llaor e amor deu haver major perfecció.
Temptà amor l'amic de saviesa, e féu-li qüestió si l'amat l'amava mes en pendre sa natura o en recrear-lo. E l'amic lo embarbesclat, tro que respòs que la recreació se convenc a esquivar malanança, e l'encarnació a donar benanança. E de la responsió lo feta altra qüestió: qual lo major amor.
Anava l'amic demanar almoina per les portes, per ço que remembràs l'amor de son amat a sos servidors, e per ço que usas d'humilitat, pobretat, paciència, qui son coses agradables a son amat.
Dernanaren perdó a l'amic per amor de son amat; e l'amic no tan solament perdonà ans los donà si mateix e sos béns.
Ab llàgremes de sos ulls recomptava l'amic la passió e la dolor que son amat sostenc per sa amor; e ab tristícia, pensaments, escrivia les paraules que deïa; e ab misericòrdia, esperança, se conhortava.
L'amat e amor vengren veer l'amic qui dormia. L'amat cridà a son amic, e amor lo despertà. E l'amic obeí a amor, e respòs a son amat.
Nodria l'amat son amic a amar; e amor ensenyava-li a perillar, e paciència l'adoctrinava con sostengués treballs per l'amor d'aquell a qui s'és donat per servidor.
Demanava l'amat a les gents si havien vist son amic, e ells demanaren-li les calitats de son amic; e l'amat dix que son amic era ardit, temerós, ric e pobre, alegre, trist, consirós, e llanguia tots jorns per sa amor.
E demanaren a l'amic si volia vendre son desirer; e ell respòs que venut l'havia a son amat per un tal diner que tot lo món ne poria ésser comprat.
—Preïca, foll, e digues paraules de ton amat. Plora, dejuna! Renuncia al món l'amic, e anà cercar son amat ab amor, e lloava—lo en aquells llocs on era deshonrat.
Bastia e obrava l'amic una bella ciutat on estegués son amat. Ab amor, pensaments, plants, plors e llanguiments l'obrava; e ab plaers, esperança, devoció, l'ornava; e ab fe, justícia, prudència, fortitudo, temprança, la guarnia.
Bevia l'amic amor en la font de son amat, en la qual l'amat llavà los peus a son amic, qui moltes vegades ha oblidats, menyspreats, sos honraments; per què lo món és en defalliment.
—Digues, foll: què és pecat? Respòs: —Entenció girada e enversada contra la final entenció e raó per què mon amat ha creades totes coses.
Veïa l'amic que el món és creat, com sia cosa que eternitat se covenga mills ab son amat, qui és essència infinida en granea e en tota perfecció, que ab lo món, qui ha cantitat finida. E, per amo en la justícia de son amat vela l'amic que l'eternitat de son amat cové ésser davant a temps e a quantitat finida.
Escusava l'amic son amat a aquells qui deien que el món és eternal, dient que son amat no hagra justícia perteta si no retés a cascuna ànima son cors; a lo qual no fóra bastant lloc ni matèria ordial; ni el món no fóra ordenat a una fi tan solament si los eternal; e si no ho fos, defallira en son amat perfecció de volentat, saviea.
—Digues, foll: ¿en què has coneixença que la fe catòlica sia vera, e la creença dels jueus e dels sarraïns sien en falsetat e error? Respòs: —En les deu condicions del Llibre del gentil e dels tres savis.
—Digues, foll: en què comença saviea? Respòs: En fe e en devoció, qui son escala on puja l'enteniment entendre los secrets de mon amat. —E fe e devoció, ¿d'on han començament? Respòs: —De mon amat, qui inlumena fe e escalfa devoció.
Demanaren a l'amic qual cosa era major: o possibilitat, o impossibilitat. Repòs que possibilitat era major en creatura, e impossibilitat en son amat; con sia cosa que possibilitat e potència se concorden, e impossibilitat e actualitat.
—Digues, foll: ¿qual cosa és major: o diferència, o concordança? Respòs que, fora son amat, diferència era major en pluralitat, e concordança en unitat, mas en son amat eren eguals en diferència e unitat.
—Digues, amador: què és valor? Respós que lo contrari de la valor d'aquest món, la qual és desirada per los falses amadors vanaglorioses, qui volen valer havents desvalor o per ésser perseguidors de valor.
—Digues, foll: has vist home qui sia orat? Respòs que ell havia vist un bisbe qui havia a sa taula molts anaps e moltes escudelles e talladors d'argent, e havia en sa cambra moltes vestedures e gran llit, e en ses caixes molts diners; e a la porta de son palau havia pocs pobres.
—Foll: saps què és viltat? Respòs: —Vils pensaments.-—E què és lleialtat? —Temor de mon amat, nada de caritat e de vergonya, qui tem blasme de les gents. —E què és honrament? Respós: —Cogitar mon amat, e desirar e lloar sos honraments.
Los treballs e les tribulacions que l'amic sostenia per amor, l'alteraren e l'enclinaren a impaciència; e représ-lo l'amat ab sos honraments e ab sos prometiments, dient que poc sabia d'amor qui s'alterava per maltrets ni per benanança. Hac l'amic contrició e plors, e pregà son amat que li retés amors.
—Fol, digues: què és amor? Respòs que amor és aquella cosa qui los francs met en servitud e a los serfs dóna llibertat. E és qüestió a qual és pus prop amor: o a llibertat, o a servitud.
Cridava l'amat son amic, e ell li responia dient: ¿Què et plau, amat que est ulls de mos ulls, e pensament de mos pensaments, e compliment de mos compliments, e amor de mes amors, e encara començament de mos començaments?
Amat —deïa l'amic—: a tu vaig e en tu vaig, car m'apelles. Contemplar vaig contemplació, ab contemplació de ta contemplació. En ta virtut so, e ab ta virtut venc, d'on prenc vertut. Salut-te ab ta salutació, qui és ma salutació en ta salutació, de la qual esper salutació perdurable en benedicció de ta henedicció, en la qual beneït son en ma benedicció.
—Alt est, amat, en tes altees, a les quals exalces ma volentat, exalçada en ton exalçament ab ta altea, qui exalça en mon remembrament mon enteniment, exalçat en ton exalçament, per conèixer tos honraments e per ço que la volentat n'haja exalçat enamorament e la memoria n'haja alta remembrança.
—Glòria est, amat, de ma glòria; e ab ta glòria e en ta glòria,—dónes glòria a ma glòria, qui ha glòria de ta glòria. Per la qual tua glòria me son glòria, egualment, los treballs e los llanguiments qui em vénen per honrar ta glòria ab los plaers e els pensaments qui em vénen de ta glòria.
—Amat: en lo carçre d'amor me tens enamorat ab tes amors, qui m'han enamorat de tes amors, per tes amors e en tes amors. Cor àls no est mas amors, en les quals me las estar sol e ab companyia de tes amors e de tos honraments. Car tu est sol en mi sol, qui son solitari ab mos pensaments, con la solitat tua, sola en honors, m'haja sola a lloar e honrar ses valors, sens temor dels desconeixents qui no t'han sol en llurs amors.
—Solaç est, amat, de solaç; per què en tu assolaç mos pensaments ab ton solaç, qui és solaç e confort de mos llanguiments e de mes tribulacions, qui son tribulades en ton solaç con no assolaces los innorants ab ton solaç e com los coneixents de ton solaç no enamores pus fortment a honrar tos honraments.
Clamava's l'amic, a son senyor, de son amat, e a son amat de son senyor. Deien lo senyor e l'amat: —¿Qui fa en nos departiment, qui som una cosa tan solament? Responia l'amic e deïa que pietat de senyor e tribulació per amat.
Perillava l'amic en lo gran pèlag d'amor, e conflava's en son amat, qui li acorria ab tribulacions, pensaments, llàgremes e plors, sospirs e llanguiments, per ço cor lo pèlag era d'amors, e d'honrar ses honors.
Alegrava's l'amic cor era son amat, cor per son ésser es tot altre ésser esdevengut, e sostentat, e obligat, e sotsmès a honrar, servir, l'ésser de son amat, qui per null ésser no pot ésser delit, ni encolpat, ni minvat ni crescut.
—Amat: en la tua granea las grans mos desirers, e mos pensaments, e mos treballs; cor tant és gran, que tota res és gran que de tu ha membrança, e enteniment e plaer; e ta granea fa poques totes coses qui son contra tos honraments, manaments.
—Eternalment comença, e ha començat e començarà mon amat; e eternalment no comença ni ha començat ni començarà. E aquests començaments no són contradicció en mon amat, per ço cor és eternal, e ha en si unitat e trinitat.
—Lo meu amat és un, e en sa unitat s'uneixen en una volentat mos pensaments e mes amors; e la unitat de mon amat abasta a totes unitats e a totes pluralitats; e la pluralitat qui és en mon amat abasta a totes unitats e pluralitats.
—Sobirà bé és lo bé de mon amat, qui és bé de mon bé; cor és bé mon amat sens altre bé, cor si no ho los, mon bé fóra d'altre he sobirà. E cor no ho és, sia doncs tot lo meu bé despès en esta vida, a honrar lo sobirà bé, cor enaixí cové.
—Sí tu, amat, saps mi pecador, si et las tu piadòs e perdonador. E cor ço que saps en tu és mellor que mi, doncs jo sé en tu perdó e amor, pus que tu las saber a mi contrició, e dolor, e desirer de pendre mort per lloar ta valor.
—Lo teu poder, amat, me pot salvar per benignitat, pietat e perdó, e pot-me damnar per justícia e per colpes de mes falliments. Complesca ton poder ton voler en mi; cor tot és compliment, sia que em dons salvació o damnament.
Amat: veritat visita la contrició de mon cor, e puja aigua a mos ulls coro ma volentat l'ama; e cor la tua veritat és sobiranà, puja veritat sajús ma volentat, a honrar tos honraments, e davalla-la a desamar mos defalliments.
—Anc ver no lo ço en què mon amat no lo, e fals és ço en què mon amat no és, e fals serà ço en què mon amat no serà. E, per açò de necessitat es que sia veritat tot quant serà, ni lo, ni és, si mon amat hi és; e per açò fals és qui és en ver on mon amat no és, sens que no se'n segueix contradicció.
Creà l'amat e destruí l'amic. Jutjà l'amat, plorà l'amic. Recrea l'amat, glòria a l'amic. Fení l'amat sa operació, e romàs l'amic eternalment en companyia de son amat.
Per les carreres de vegetació, e de sentiment, e d'imaginació, e d'enteniment, volentat, anava l'amic cercar son amat; e en aquelles carreres havia l'amic perills e llanguiments per son amat, per ço que exalçàs son enteniment e sa volentat a son amat, qui vol que els seus amadors l'entenen e l'amen altament.
Mou-se l'amic a ésser per l'acabament de son amat, e mou-se a no ésser per son defalliment. E per açò és qüestió qual dels dos moviments han major apoderament en l'amic naturalment.
—Posat m'has, amat, enfre mon mal e ton bé. A la tua part sia pietat, misericòrdia, paciència, humilitat e perdó, ajuda e restaurament; a la mia part sia contrició, perseverança, membrança, ab sospirs, llàgremes e plors, de la tua santa passió.
—Amat qui em las amar: si no m'ajudes, per què em volguist crear? ¿Ni per què per mi portest tantes llangors, ni sostenguist tan greu passió? Pus tant m'has ajudat a exalçar, ajuda'm, amat, a davallar, a membrar, aïrar, mes colpes e mos defalliments, per ço que mills mos pensaments pusquen pujar a desirar, honrar, lloar tes valors.
—Mon voler has fet franc a amar tos honraments, e a menysprear tes valors, per ço que pusques a mon voler muntiplicar tes amors.
—En aquesta llibertat has, amat, perillada ma volentat. Amat: en aquest perill deus remembrar ton amic, qui de sa volentat franca trau servitud a lloar tes honors e a muntiplicar en son cors llanguiments e plors.
—Amat: anc de tu en ton amic no venc colpa ni falliment, ni en ton amic compliment sens ton do e perdó. E doncs, pus l'amic t'ha en aital possessió, no l'hages en oblit en ses tribulacions ni en son perillament.
—Amat, qui en un nom est nomenat hom e Déu! En aquell nom, Jesucrist, te vol ma volentat home e Déu; e si tu, amat, has tant honrat ton amic sens sos mérits, en nomenar e voler ton nom, ¿per què no honres tants hòmens innorables qui cientalment no són estats tan colpables al ten nom, Jesucrist, con és estat lo teu amic?
Plorava l'amic, e deïa a son amat aquestes paraules: —Amat: no fuist anc avar ni cóbeu al teu amic en donar ésser, ni en recrear-lo, ni en donar-li moltes creatures a son servii. Doncs, ¿d'on vendria, amat, que tu, qui est sobirana llibertat, fosses avar a ton amic, de plors, pensaments, llanguiments, saviea e amors, a honrar tes honors? E per açò, amat, lo teu amic te demana vida llonga, per tal que pusca reebre de tu molts dels dons damunt dits.
—Amat: si tu ajudes als hòmens justs, de llurs mortais enemics, ajuda a muntiplicar mos pensaments en desirar tes honors; e si tu ajudes als hòmens injusts, com recobren justícia, ajuda al ten amic com faga de sa volentat sacrifica a ta llaor, e de son cors, a testimoni d'amor per vía de martire.
—No ha mon amat diferència en humilitat, humil, humiliat, cor tot es humilitat en pura actualitat. E per açò l'amic reprèn ergull, qui vol pujar a son amat aquells qui en est món la humilitat de mon amat ha tant honrats, e ergull los ha vestits d'hipocresia, vanaglòria, vanitats.
Humilitat ha humiliat l'amat a l'amic, per contrición e sí es féu per devoció. E és qüestió en qual d'ambdues l'amat los pus fortment humillat a l'amic.
Hac l'amat, per sa perfecció, misericòrdia, de son amic, e sí hac per les necessitats de son amic. E lo qüestió per qual de les dues raons l'amat perdona pus fortment les colpes de son amic.
—Pregaven nostra Dona e los àngels e els sants de glòria mon amat; e coro remembré l'error en què el món és per desconeixença, membré gran la justícia de mon amat, e gran la desconeixença de sos enemics.
Pujava l'amic los poders de sa ànima, per escala d'humanitat, gloriejar la divina natura; e per la divinas natura davallava los poders de sa ànima per gloriejar en la humana natura de son amat.
On pus estretes son les vies on l'amic va a son amat, pus amples son les amors; e on pus estretes son les amors, pus amples son les vies. E per açò, en totes maneres ha l'amic per son amat amors e treballs, e llanguiments e plaers e consolacions.
Ixen amors d'amors, e pensaments de llanguiments, e plors de llanguiments; e entren amors en amors, e pensaments en plors, e llanguiments en sospirs. E l'amat esguarda's son amic, qui ha per sa amor totes aquestes tribulacions.
Tranuitaven e faïen romeries e pelegrinacions los desirers e els remembraments de l'amic en les noblees de son amat, e aportaven a l'amic faiçons, e omplien son enteniment de resplendor, per la qual la volentat muntiplicava ses amors.
L'amic, ab sa imaginación pintava e formava les faiçons de son amat en les coses corporals, e ab son enteniment les polia en les coses esperituals, e ab volentat les adorava en totes creatures.
Comprà l'amic un dia de plors per altre dia de pensaments, e vené un dia d'amors per altre de tribulacions; e muntiplicaren ses amors e sos pensaments.
Era l'amic en terra estranya, e oblidà son amat, e enyorá's de son senyor e sa muller e sos infants, e de sos amics. Mas retornà remembrar son amat, per ço que los consolat e que la sua estranyedat no li donàs enyorament ni marriment.
Oïa l'amic paraules de son amat, en les quals lo veia son enteniment, per ço cor la volentat havia plaer d'aquell oïment; e lo remembrament membrava les virtuts de son amat, e los seus prometiments.
Oïa blasmar l'amic son amat, en lo qual blasme veïa l'enteniment la justícia e la paciència de son amat, cor la justícia punia los blasmadors, e la paciència los esperava a contrición penediment. E per açò és qüestió en qual dels dos l'amic creïa pus fortment.
Malalt fo l'amic, e féu testament ab consell de son amat. Colpes e torts lleixà a penediment, penitència; e delits temporals lleixà a menyspreament; a sos ulls lleixà plors, e a son cor sospirs e amors; e a son enteniment lleixà les faiçons de son amat; e a son remembrament la passió que sostenc per sa amor son amat; e a son negoci lleixà l'endrecament dels infeels, qui innorantment van a perdiment.
Odorà l'amic flors, e remembrà pudors en ric avar, e en luxuriós, e en desconeixent ergullós. Gustà l'amic dolcors, e entés amargors en les possessions temporals, e en l'entrament e iximent d'aquest món. Sentí l'amic plaers temporals, e l'enteniment entès lo breu traspassament d'aquest món e los perdurables turments als quals són ocasió los delits qui a aquest món són agradables.
Hac l'amic fam, set, calor e fred, pobretat, nuedat, olalaltia, tribulación e fóra finit si no hagués membrança de son amat, qui el sanà ab esperança remembrament, e ab lo renunciament d'aquest món, e ab lo menyspreament del blasme de la gent.
Enfre treball e plaer era lo llit de l'amic: ab plaer s'adormia, e ab treball se despertava. E és qüestió a quals d'aquests dos és pus prop lo llit de l'amic.
En ira s'adormí l'amic, cor temia lo blasme de la gent; e despertà's en paciència, com remembrà llaors de son amat. E és qüestió l'amic de qui hac major vergonya: o de son amat, o de les gents.
Cogità l'amic en la mort. e hac paor tro que remembrà la ciutat de son amat, de la qual, mort e amor són portals e entrament.
Clamavàs l'amic a son amat de temptacions qui li venien tots jorns treballar sos pensaments. E l'amat li respòs dient que temptacions són ocasió com hom recorra ab remembrament remembrar Déu e amar sos honrats capteniments.
Perdé l'amic una joia que molt amava; e fóra's desconsolat, tro que son amat li féu qüestió qual cosa li era pus profitable: o la joia que havia, o la paciència que hae en les obres de son amat.
Dormia l'amic considerant en los treballs e els empatxaments los quals ha en servir son amat, e hac paor que ses obres no perissen per aquells empatxaments. Mas l'amat li tramès consciència qui el despertà en sos mèrits e en los poders de son amat.
Havia l'amic a anar llongues carreres, e dures e aspres; e era temps que anàs per aquelles e que portàs lo gran feix que amor fa portar a sos amadors. E per açò l'amic alleujà sa ànima dels pensaments e els plaers temporals, per ço que el cors pogués portar lo càrrec pus lleugerament, e l'ànima anàs per aquelles carreres en companyia ab son amat.
Denant l'amic deïen un jorn mal de son amat, sens que l'amic no hi respòs ni escusà son amat. E és qüestió qual es pus encolpat: o els hòmens qui blasmaven l'amat, o l'amic qui callava e no escusava son amat.
Contemplant l'amic son amat, s'assubtilava en son enteniment, e enamorava's en sa volentat. E és qüestió per qual dels dos assubtilava pus fortment sa remembrança a remembrar son amat.
Ab frevor e temor anava l'amic en son viatge honrar son amat: frevor lo portava, temor lo conservava. Dementre que l'amic enaixí anava, atrobà sospirs e plors qui li aportaven saluts de son ainat. E és qüestió per qual de tots quatre lo mills assolaçat l'amic en son amat.
Esguardava l'amic si mateix per ço que los mirall on veés son amat, e esguardava son amat per ço que li los mirall on hagués coneixença de si mateix. E és qüestió a qual dels dos miralls era son enteniment pus acostat.
Teologia e Filosofia, Medicina e Dret encontraren l'amic qui els demanà de noves si havien vist son amat. Teologia plorava, Filosofia dubtava, Medicina e Dret s'alegraven. E és qüestió què signifiquen cascú dels quatre significats a l'amic qui va cercar son amat.
Angoixós e plorós anava l'amic encercar son amat per vies sensuals e per carreres entel·lectuais. E és qüestió en qual dels dos camins entra primerament dementre cercava son amat, ni en qual l'amat se mostrá a l'amic pus declaradament.
El dia del judici dirà l'amat que hom tris a una part ço que en aquest món li ha donat, e a altra part sia triat ço que hom ha donat al món, per ço que sia vist com coralment és estat amat, ni qual deis dos dons és pus noble e de major cantitat,
Amava la volentat de l'amic si mateixa, e l'enteniment demanà-li si era pus semblant a son amat en amar si mateixa o en amar son amat, com sia cosa que son amat sia pus amant si mateix que nulla altra cosa. E per açò és qüestió segons qual responsió la volentat poe respondre a l'enteniment pus vertaderament.
—Digues, foll: ¿qual és la major e la pus noble amor que sia en creatura? Respòs: —Aquella qui és una ab lo creador —Per què? —Per ço cor lo creador no ha en què pusca fer pus noble creatura.
Estava l'amic un dia en oració, e sentí que sos ulls no ploraven; e per ço que pogués plorar tramès sa cogitació cogitar en diners, fembres, fills, viandes, vanaglòria; e atrobà en son enteniment que mes gents han a servidors cascunes de les coses damunt dites, que no ha son amat. E per açò foren sos ulls en plors, e sa ànima en tristícia e en dolor.
Anava l'amic consirós en son amat, e atrobà en la via grans gents e grans companyes qui li demanaven de noves; e l'amic, per ço cor atrobava plaer en son amat, no respòs a ço que li demanaven, e dix que per ço que no es llunyàs de son amat no volia respondre a llurs paraules.
Era l'amic dintre e defora cobert d'amor, e anava cercar son amat. Deïa-li amor: on vas, amador? Respòs: —Vaig a mon amat per ço que tu sies major.
—Digues, foll: què és religió? Respòs: —Nedeetat de pensa, e desirar morir per honrar mon amat, e renunciar al món per ço que no haja embargament a contemplar-lo e a dir veritat de sos honraments.
—Digues, foll: ¿què són treballs, piants, sospirs, piors, tribulacions, perills, en amic? Respòs: —Plaer d'amat. —Per què? —Per ço que en sia més amat, e l'amic més guaardonat.
Demanaren a l'amic amor en qual era major: o en l'amic qui vivia, o en l'amic qui moria. Respòs que en l'amic qui moria. —Per què? —Per ço cor no pot ésser major en amic qui mor per amor, e pot-ho ésser en amic qui viu per amor.
Encontraren-se dos amics; la un mostrava son amat, e l'altre l'entenia. E era qüestió qual d'ambdós era pus prop a son amat. E per la solució l'amic havia coneixença de la demostració de trinitat.
—Digues, foll: per què parles tan subtilment? Respòs: —Per ço que sia ocasió a exalçar enteniment a les noblees de mon amat, e perquè per més hòmens sia honrat, amat e servit.
Embriagava's l'amic de vi, qui membrava, entenia e amava l'amat. Aquell vi amarava l'amat ab sos plors e ab les llàgremes de son amic.
Amor escalfava e afiamava l'amic en membrança de son amat; e l'amat lo refredava ab llàgremes e plors, e ab oblidament dels delits d'aquest món, e ab renunciament dels vans honraments. E creixien les amors com l'amic membrava per qui sostenia llangors, tribulacions, ni los hómens mundans per qui sostenien treballs, persecucions.
—Digues, foll: què és aquest món? Respòs: —Presó dels amadors, servidors, de mon amat —E qui els met en presó? Respòs: Consciència, amor, temor, renunciament, contrició, companyia d'àvol gent; e és treball sens guardó, on és puniment.
"""

thenow = date.today()
theend = date(thenow.year,thenow.month,thenow.day)
theone = date(thenow.year,1,1)
theday = (theend - theone).days

if (theday < 0) or (theday > 366):
    exit("Something went wrong with the calculations. Sorry.")

verses = thetext.split('\n')

# There's a blank line, so we can use the day
# without subtracting to make 1 january = 0
print("%d. %s") % (theday, verses[theday])
